ITEM.name = "Cooking Pan"
ITEM.description = "itemCookingPanDesc"
ITEM.class = "weapon_hl2pot"
ITEM.classes = {CLASS_CWU}
ITEM.category = "misc"
ITEM.weaponCategory = "melee"
ITEM.price = 25
ITEM.model = "models/weapons/hl2meleepack/w_pot.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.isjunk = true