ITEM.name = "Frying Pan"
ITEM.description = "itemFryingPanDesc"
ITEM.class = "weapon_hl2pan"
ITEM.classes = {CLASS_CWU}
ITEM.category = "misc"
ITEM.weaponCategory = "melee"
ITEM.price = 25
ITEM.model = "models/weapons/hl2meleepack/w_pan.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.isjunk = true