ITEM.name = "Antlion Grub"
ITEM.model = "models/ccr/props/grub_vial_full.mdl"
ITEM.description = "itemAntlionGrubDesc"
ITEM.category = "Utility"
ITEM.factions = {FACTION_OTA, FACTION_MPF, FACTION_CONSCRIPTS}
ITEM.classes = nil
ITEM.hunger = -10
ITEM.thirst = -5
ITEM.price = 60
ITEM.heal = 5
ITEM.empty = "antlion_grub_empty"
ITEM.usenum = 4
ITEM.sound = "interface/inv_eat_mutant_food.ogg"